[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.10.1",
    "gensim>=4.3.3",
    "pandas>=2.3.2",
    "tiktoken>=0.11.0",
    "torch>=2.8.0",
    "transformers>=4.56.1",
]
