[project]
name = "crewai-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.148.0",
    "crewai-tools>=0.55.0",
]

[tool.poetry.scripts]
crewai_quickstart = "crewai_quickstart.main:run"